# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 300))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_opened_file = QtWidgets.QLabel(self.centralwidget)
        self.lbl_opened_file.setObjectName("lbl_opened_file")
        self.gridLayout.addWidget(self.lbl_opened_file, 0, 1, 1, 1)
        self.radioBtn_image = QtWidgets.QRadioButton(self.centralwidget)
        self.radioBtn_image.setObjectName("radioBtn_image")
        self.gridLayout.addWidget(self.radioBtn_image, 1, 1, 1, 1)
        self.chbx_compress = QtWidgets.QCheckBox(self.centralwidget)
        self.chbx_compress.setEnabled(False)
        self.chbx_compress.setChecked(True)
        self.chbx_compress.setObjectName("chbx_compress")
        self.gridLayout.addWidget(self.chbx_compress, 4, 1, 1, 1)
        self.chbx_format_img = QtWidgets.QCheckBox(self.centralwidget)
        self.chbx_format_img.setEnabled(False)
        self.chbx_format_img.setChecked(True)
        self.chbx_format_img.setObjectName("chbx_format_img")
        self.gridLayout.addWidget(self.chbx_format_img, 5, 1, 1, 1)
        self.chbx_format_pal = QtWidgets.QCheckBox(self.centralwidget)
        self.chbx_format_pal.setEnabled(False)
        self.chbx_format_pal.setChecked(True)
        self.chbx_format_pal.setObjectName("chbx_format_pal")
        self.gridLayout.addWidget(self.chbx_format_pal, 6, 1, 1, 1)
        self.txt_resource_name = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_resource_name.setObjectName("txt_resource_name")
        self.gridLayout.addWidget(self.txt_resource_name, 3, 1, 1, 1)
        self.lbl_options = QtWidgets.QLabel(self.centralwidget)
        self.lbl_options.setObjectName("lbl_options")
        self.gridLayout.addWidget(self.lbl_options, 4, 0, 1, 1)
        self.lbl_resource_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resource_name.setObjectName("lbl_resource_name")
        self.gridLayout.addWidget(self.lbl_resource_name, 3, 0, 1, 1)
        self.radioBtn_raw = QtWidgets.QRadioButton(self.centralwidget)
        self.radioBtn_raw.setObjectName("radioBtn_raw")
        self.gridLayout.addWidget(self.radioBtn_raw, 2, 1, 1, 1)
        self.btn_load_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_file.setObjectName("btn_load_file")
        self.gridLayout.addWidget(self.btn_load_file, 0, 0, 3, 1)
        self.lst_resources = QtWidgets.QListView(self.centralwidget)
        self.lst_resources.setObjectName("lst_resources")
        self.gridLayout.addWidget(self.lst_resources, 1, 2, 6, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add_resource = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_resource.setEnabled(False)
        self.btn_add_resource.setObjectName("btn_add_resource")
        self.horizontalLayout.addWidget(self.btn_add_resource)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_remove_resource = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_resource.setEnabled(False)
        self.btn_remove_resource.setObjectName("btn_remove_resource")
        self.horizontalLayout.addWidget(self.btn_remove_resource)
        self.btn_save_header = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_header.setEnabled(False)
        self.btn_save_header.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_save_header.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_save_header.setObjectName("btn_save_header")
        self.horizontalLayout.addWidget(self.btn_save_header)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 3)
        self.lbl_loaded_resources = QtWidgets.QLabel(self.centralwidget)
        self.lbl_loaded_resources.setObjectName("lbl_loaded_resources")
        self.gridLayout.addWidget(self.lbl_loaded_resources, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Header file generator"))
        self.lbl_opened_file.setText(_translate("MainWindow", "No file opened."))
        self.radioBtn_image.setText(_translate("MainWindow", "Image"))
        self.chbx_compress.setText(_translate("MainWindow", "Compress data"))
        self.chbx_format_img.setText(_translate("MainWindow", "Format image data"))
        self.chbx_format_pal.setText(_translate("MainWindow", "Format palette data"))
        self.lbl_options.setText(_translate("MainWindow", "Options:"))
        self.lbl_resource_name.setText(_translate("MainWindow", "Resource name:"))
        self.radioBtn_raw.setText(_translate("MainWindow", "Raw"))
        self.btn_load_file.setText(_translate("MainWindow", "Load File"))
        self.btn_add_resource.setText(_translate("MainWindow", "Add Resource"))
        self.btn_remove_resource.setText(_translate("MainWindow", "Remove Resource"))
        self.btn_save_header.setText(_translate("MainWindow", "Save Header"))
        self.lbl_loaded_resources.setText(_translate("MainWindow", "Loaded resources:"))

